whiteapp/DjangoSite/urls.py
from WhiteApp.views import Accueil
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path

urlpatterns = [
    path('', Accueil.as_view(), name='Accueil'),
    path('WhiteApp/', include('WhiteApp.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

whiteapp/WhiteApp/urls.py
# -*- coding: utf-8 -*-
# ================================================= Import des packages ================================================
from django.urls import path

from . import views

# ============================= Definition des variables ===============================================================
app_name = 'WhiteApp'
urlpatterns = [
    path('Accueil', views.Accueil.as_view(), name="Accueil"),
    path('AccueilVue', views.AccueilVue.as_view(), name="AccueilVue")
]

whiteapp/WhiteApp/models.py
"""
Django models
"""
# -*- coding: utf-8 -*-
# ================================================= Import des packages ================================================
# Gestion des données
from uuid import uuid4

# Package Django
from django.db import models
from django.forms import ModelForm

# ============================= Definition des variables ===============================================================

creation_date_name = "Creation date"
updated_at_name = "Last update"


# ============================= Definition des fonctions ===============================================================
def _generate_unique_uri():
    return str(uuid4()).replace("-", "")[:15]


# ============================= Definition des classes =================================================================
class WhiteApp(models.Model):
    created_at = models.DateTimeField(creation_date_name, auto_now_add=True)
    updated_at = models.DateTimeField(updated_at_name, auto_now=True)
    uri = models.CharField(default=_generate_unique_uri, max_length=15, primary_key=True)
    nom_projet = models.CharField("Nom du projet", max_length=200)

    layout = {"Informations générales": ["nom_projet"]}

    @property
    def exemple_propriete(self):
        return self.nom_projet

    def to_dict(self, **kwargs):
        """
        Turns itself into a dict (easily readable)
        :return:
        :rtype: dict
        """
        result = {v: self.__getattribute__(v) for k, v in self.layout.items()}
        result.update({"uri": self.uri})

        result.update(kwargs)
        return result

    def to_Accueil_view(self, **kwargs):
        """
        Fonction utilisée pour exporter les données relatives à un projet (utilisée par les views)
        :return:
        :rtype: dict
        """
        result = self.to_dict(**kwargs)
        return result

    def __str__(self):
        return "{} - ({})".format(self.nom_projet, self.uri)

    def save(self, *args, **kwargs):
        super(WhiteApp, self).save(*args, **kwargs)


class WhiteAppForm(ModelForm):
    class Meta:
        model = WhiteApp
        exclude = ["created_at", "updated_at"]

    layout = WhiteApp.layout

whiteapp/WhiteApp/views.py
# -*- coding: utf-8 -*-
# ================================================= Import des packages ================================================
import codecs
import os
import re
import sys

import pandas as pd
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic.base import TemplateView
from pip._internal.operations.freeze import freeze
from markupsafe import Markup
import logging as logger


# ============================= Definition des classes  ================================================================
class Accueil(TemplateView):
    login_url = "/login/"
    redirect_field_name = "redirect_to"
    template_name = "Accueil.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {})


class AccueilVue(TemplateView):
    login_url = '/login/'
    redirect_field_name = 'redirect_to'

    def post(self, request):
        logger.warning("POST : IN : request : {}".format(request))

        result = {"messages": []}

        request_dict = request.POST.dict()

        if "init" in request_dict:
            result['user'] = None

        with codecs.open(os.path.join(os.path.dirname(
                os.path.dirname(os.path.abspath(__file__))), "__init__.py"), 'r') as fp:
            version_file = fp.read()

        version_match = re.search(r"^__version__ = ['\"]([^'\"]*)['\"]", version_file, re.M)
        cell = {  # for row hover use <tr> instead of <td>
            'selector': 'td',
            'props': [('background-color', '#ffffb3'),
                      ('color', 'black')]
        }
        cell_hover = {  # for row hover use <tr> instead of <td>
            'selector': 'td:hover',
            'props': [('background-color', '#ffffb3'),
                      ('color', 'red')]
        }
        index_names = {
            'selector': '.index_name',
            'props': 'font-style: italic; color: darkgrey; font-weight:normal;'
        }
        headers = {
            'selector': 'th:not(.index_name)',
            'props': 'background-color: #000066; color: white;'
        }

        result['python_version'] = sys.version
        if version_match:
            result['package_version'] = version_match.group(1)
        else:
            "Unknown"
        result['requirements'] = Markup(pd.DataFrame(list(
            map(lambda x: x.split('=='), freeze(local_only=True))
        ), columns=['package', 'version']).style.set_table_styles(
            [cell, cell_hover, index_names, headers]).hide_index().to_html())

        result["messages"].append({
            "msg": "Succès",
            "type": "alert-success"})

        logger.warning("POST : OUT : request : {}".format(result))

        return JsonResponse(result, status=202)

whiteapp/templates/Accueil.html
{% extends "base_site.html" %}
{% load static %}

{% block head %}

{% endblock %}

{% block subtitle %}
{% endblock %}

{% block content %}

<div id="app_accueil">

    <div v-if="loading">
        <div  class="d-flex justify-content-center" >
            <div  id = "lds-ring" class="lds-ring">
                <div></div><div></div><div></div>
            </div>
        </div>
        <div class="cls-label"> Veuillez patienter ...</div>
    </div>
    <div v-else>
        <div class="d-flex justify-content-center" style="color: black;font-weight: bold;">
            Version de la whiteapp
        </div>
        <div class="d-flex justify-content-center" style="color: black;">
            ##package_version##
        </div>
        <div class="d-flex justify-content-center" style="color: black;font-weight: bold;">
            Version de Python
        </div>
        <div class="d-flex justify-content-center" style="color: black;">
            ##python_version##
        </div>
        <div class="d-flex justify-content-center" style="color: black;font-weight: bold;">
            Liste des packages utilisés et leur version
        </div>
        <div v-html="requirements"></div>
    </div>

</div>

<script>
    var app_accueil = new Vue({
        el: '#app_accueil',
        delimiters: ['##', '##'],
        data: {
        messages: [],
        requirements: [],
        init: false,
                now: Date.now(),
                loading: true},

        methods: {

            init_func(){
                data = {"csrfmiddlewaretoken": '{{ csrf_token }}',
                        "init": true,
                        }
                this.load_data(data)
            },

            load_data(data){
                var self = this;
                $.ajax({
                    url: '{% url 'WhiteApp:AccueilVue' %}',
                    data: data,
                    method: 'POST',
                    success: function(result) {
                        self.loading=true;
                        self.requirements = result.requirements
                        self.package_version = result.package_version
                        self.python_version = result.python_version

                        {# Messages d'alerte #}
                        self.messages = result.messages
                        setTimeout(function() { $(".alert").hide(); }, 10000);
                        self.loading=false;
                    },
                    error: function(error) {
                        console.log(error);
                    }
                });

            },

        },
        mounted:
           function () {
                this.init_func();
           }
    })

</script>


{% endblock %}

whiteapp/templates/login.html
{% extends "base_site.html" %}
{% load static %}


{% block name %}
    <title>Connexion</title>
{% endblock %}

{% block title %}
    Connexion
{% endblock %}

{% block content %}

    {% if form.errors %}
    <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
    {% endif %}

    <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <table aria-describedby="Users">
        <tr style="background-color:#f8f9fa00;">
            <th scope="col">{{ form.username.label_tag }}</th>
            <th scope="col">{{ form.username }}</th>
        </tr>
        <tr style="background-color:#f8f9fa00;">
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
        </tr>
        </table>

        <input type="submit" style="width:30%;" value="SE CONNECTER" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>


{% endblock %}